[arrangement]
name = "yisheng_576"
first_index = 1
last_index = 576
kit = "YS_NB"
mask1_front = "ATTGCTAAGGTTAA"
mask1_rear = "CAGCACCT"
mask2_front = "ATTGCTAAGGTTAA"
mask2_rear = "CAGCACC"
barcode1_pattern = "YS_NB-%03i"
barcode2_pattern = "YS_NB-%03i"

