#' Basecall POD5 files with Dorado
#'
#' `dorado_basecall()` runs `dorado basecaller` on a project `pod5/` directory
#' and writes a BAM file.
#'
#' @param proj Project directory containing a `pod5/` subdirectory.
#' @param model Dorado basecalling model or model alias.
#' @param output_bam Output BAM file. If `NULL`, writes
#'   `proj/bam/calls_<model>.bam`.
#' @param overwrite Logical. If `FALSE`, stop when `output_bam` already exists.
#' @param dorado Command name or executable path for `dorado`.
#' @param conda_env Optional conda environment name. If supplied, Dorado is run
#'   with `conda run -n <conda_env>`.
#' @param conda Conda executable name or path used when `conda_env` is supplied.
#' @param dry_run Logical. If `TRUE`, return planned command without running.
#' @param echo Logical. If `TRUE`, print planned command before execution.
#' @param stderr Passed to [system2()]. Defaults stream errors to the R console.
#'
#' @return Invisibly returns a list with `status`, `command`, `args`,
#'   `command_string`, `paths`, and `conda_env`.
#'
#' @export
dorado_basecall <- function(proj,
                            model = "sup",
                            output_bam = NULL,
                            overwrite = TRUE,
                            dorado = "dorado",
                            conda_env = NULL,
                            conda = "conda",
                            dry_run = FALSE,
                            echo = TRUE,
                            stderr = "") {
  check_dir_arg(proj, "proj")
  check_scalar_character(model, "model")
  check_scalar_character(dorado, "dorado")
  check_scalar_character(conda, "conda")
  check_logical_scalar(overwrite, "overwrite")
  check_logical_scalar(dry_run, "dry_run")
  check_logical_scalar(echo, "echo")
  if (!is.null(conda_env)) check_scalar_character(conda_env, "conda_env")

  proj <- normalizePath(proj, mustWork = TRUE)
  pod5_dir <- file.path(proj, "pod5")
  if (!dir.exists(pod5_dir)) {
    stop("`proj` must contain a pod5/ directory: ", pod5_dir, call. = FALSE)
  }

  if (is.null(output_bam)) {
    output_bam <- file.path(proj, "bam", paste0("calls_", model, ".bam"))
  } else {
    check_scalar_character(output_bam, "output_bam")
  }
  dir.create(dirname(output_bam), recursive = TRUE, showWarnings = FALSE)
  output_bam <- normalizePath(output_bam, mustWork = FALSE)
  if (file.exists(output_bam) && !isTRUE(overwrite)) {
    stop("`output_bam` already exists and `overwrite` is FALSE: ", output_bam,
         call. = FALSE)
  }

  args <- c("basecaller", model, paste0(pod5_dir, .Platform$file.sep))
  call <- dehost_fastq_external_call(dorado, args, conda_env, conda)
  command_string <- paste(c(shQuote(call$command), shQuote(call$args), ">", shQuote(output_bam)), collapse = " ")

  if (isTRUE(echo)) message(command_string)

  paths <- list(project_dir = proj, pod5_dir = pod5_dir, output_bam = output_bam)
  if (isTRUE(dry_run)) {
    return(invisible(list(
      status = NA_integer_,
      command = call$command,
      args = call$args,
      command_string = command_string,
      paths = paths,
      conda_env = conda_env
    )))
  }

  if (is.null(conda_env)) {
    require_external_command(dorado)
  } else {
    require_external_command(conda)
  }

  status <- system2(call$command, args = call$args, stdout = output_bam, stderr = stderr)
  if (!identical(status, 0L)) {
    unlink(output_bam)
    stop("dorado basecaller failed with exit status: ", status, call. = FALSE)
  }
  if (!file.exists(output_bam) || file.info(output_bam)$size == 0) {
    unlink(output_bam)
    stop("dorado basecaller did not create a non-empty BAM: ", output_bam,
         call. = FALSE)
  }

  invisible(list(
    status = status,
    command = call$command,
    args = call$args,
    command_string = command_string,
    paths = paths,
    conda_env = conda_env
  ))
}

#' Demultiplex a Dorado BAM file into barcode BAM folders
#'
#' `dorado_demux_bam()` runs `dorado demux` on a basecalled BAM file and writes
#' demultiplexed BAM files under a Dorado output directory.
#'
#' @param calls_bam Input BAM generated by Dorado basecalling.
#' @param demux_dir Output directory passed to `dorado demux --output-dir`.
#' @param kit_name Dorado barcode kit name. Use `"YS-NB576"` for the ONTools
#'   built-in 576-sample custom barcode set.
#' @param barcode_both_ends Logical. If `TRUE`, pass `--barcode-both-ends`.
#' @param emit_summary Logical. If `TRUE`, pass `--emit-summary`.
#' @param threads Optional thread count passed to `dorado demux --threads`.
#' @param require_bam_pass Logical. If `TRUE`, stop when no demultiplexed BAM
#'   files are found under `demux_dir` after Dorado finishes.
#' @param barcode_config_dir Optional directory containing custom barcode
#'   configuration files. If `NULL`, uses `ONTOOLS_BARCODE_CONFIG_DIR` or the
#'   package bundled `docs/barcode_configs` directory.
#' @param dorado Command name or executable path for `dorado`.
#' @inheritParams dorado_basecall
#'
#' @return Invisibly returns a list with `status`, `command`, `args`,
#'   `command_string`, `paths`, and `conda_env`.
#'
#' @export
dorado_demux_bam <- function(calls_bam,
                             demux_dir,
                             kit_name = "EXP-NBD196",
                             barcode_both_ends = TRUE,
                             emit_summary = TRUE,
                             threads = NULL,
                             require_bam_pass = TRUE,
                             barcode_config_dir = NULL,
                             dorado = "dorado",
                             conda_env = NULL,
                             conda = "conda",
                             dry_run = FALSE,
                             echo = TRUE,
                             stderr = "") {
  check_file_arg(calls_bam, "calls_bam")
  check_scalar_character(demux_dir, "demux_dir")
  check_scalar_character(kit_name, "kit_name")
  check_scalar_character(dorado, "dorado")
  check_scalar_character(conda, "conda")
  check_logical_scalar(barcode_both_ends, "barcode_both_ends")
  check_logical_scalar(emit_summary, "emit_summary")
  check_logical_scalar(require_bam_pass, "require_bam_pass")
  check_logical_scalar(dry_run, "dry_run")
  check_logical_scalar(echo, "echo")
  if (!is.null(conda_env)) check_scalar_character(conda_env, "conda_env")
  if (!is.null(barcode_config_dir)) check_dir_arg(barcode_config_dir, "barcode_config_dir")
  threads <- validate_optional_positive_integer(threads, "threads")

  calls_bam <- normalizePath(calls_bam, mustWork = TRUE)
  dir.create(demux_dir, recursive = TRUE, showWarnings = FALSE)
  demux_dir <- normalizePath(demux_dir, mustWork = TRUE)

  args <- c("demux", "--output-dir", demux_dir)
  if (isTRUE(emit_summary)) args <- c(args, "--emit-summary")
  if (!is.null(threads)) args <- c(args, "--threads", as.character(threads))

  custom_paths <- dorado_custom_barcode_paths(kit_name, barcode_config_dir)
  if (is.null(custom_paths)) {
    args <- c(args, "--kit-name", kit_name)
  } else {
    args <- c(
      args,
      "--kit-name", kit_name,
      "--barcode-arrangement", custom_paths$arrangement,
      "--barcode-sequences", custom_paths$sequences
    )
  }
  if (isTRUE(barcode_both_ends)) args <- c(args, "--barcode-both-ends")
  args <- c(args, calls_bam)

  call <- dehost_fastq_external_call(dorado, args, conda_env, conda)
  command_string <- paste(c(shQuote(call$command), shQuote(call$args)), collapse = " ")
  if (isTRUE(echo)) message(command_string)

  paths <- list(calls_bam = calls_bam, demux_dir = demux_dir)
  if (!is.null(custom_paths)) {
    paths$barcode_arrangement <- custom_paths$arrangement
    paths$barcode_sequences <- custom_paths$sequences
  }

  if (isTRUE(dry_run)) {
    return(invisible(list(
      status = NA_integer_,
      command = call$command,
      args = call$args,
      command_string = command_string,
      paths = paths,
      conda_env = conda_env
    )))
  }

  if (is.null(conda_env)) {
    require_external_command(dorado)
  } else {
    require_external_command(conda)
  }

  status <- system2(call$command, args = call$args, stderr = stderr)
  if (!identical(status, 0L)) {
    stop("dorado demux failed with exit status: ", status, call. = FALSE)
  }
  if (isTRUE(require_bam_pass) && !dorado_demux_has_bam_pass(demux_dir)) {
    stop("dorado demux finished but no BAM files were found under bam_pass/ in: ",
         demux_dir, call. = FALSE)
  }

  invisible(list(
    status = status,
    command = call$command,
    args = call$args,
    command_string = command_string,
    paths = paths,
    conda_env = conda_env
  ))
}

dorado_demux_has_bam_pass <- function(demux_dir) {
  all_dirs <- list.dirs(demux_dir, recursive = TRUE, full.names = TRUE)
  bam_pass_dirs <- all_dirs[basename(all_dirs) == "bam_pass"]
  any(vapply(
    bam_pass_dirs,
    function(path) {
      length(list.files(path, pattern = "[.]bam$", recursive = TRUE)) > 0L
    },
    logical(1)
  ))
}

#' Convert Dorado demultiplexed BAM folders to FASTQ.GZ
#'
#' `dorado_bam_to_fastq()` searches for Dorado `bam_pass/` directories under a
#' demultiplexing output directory and converts each barcode BAM folder to a
#' matching `fastq.gz` file.
#'
#' @param demux_dir Dorado demultiplexing output directory containing one or
#'   more `bam_pass/` directories.
#' @param fastq_out FASTQ output directory name created next to each `bam_pass/`
#'   directory.
#' @param overwrite Logical. If `FALSE`, stop when an output FASTQ already
#'   exists.
#' @param include_unclassified Logical. If `FALSE`, skip `unclassified/` BAM
#'   folders.
#' @param allow_empty Logical. If `FALSE`, stop when a converted FASTQ.GZ has no
#'   FASTQ records.
#' @param samtools,gzip Command names or executable paths for `samtools` and
#'   `gzip`.
#' @inheritParams dorado_basecall
#'
#' @return Invisibly returns a list with `status`, `commands`, `conversions`,
#'   `paths`, and `conda_env`. `conversions` is a data frame with barcode BAM
#'   directories, output FASTQ paths, and the number of BAM files converted.
#'
#' @export
dorado_bam_to_fastq <- function(demux_dir,
                                fastq_out = "fastq_pass_trim",
                                overwrite = TRUE,
                                include_unclassified = TRUE,
                                allow_empty = FALSE,
                                samtools = "samtools",
                                gzip = "gzip",
                                conda_env = NULL,
                                conda = "conda",
                                dry_run = FALSE,
                                echo = TRUE,
                                stderr = "") {
  check_dir_arg(demux_dir, "demux_dir")
  check_scalar_character(fastq_out, "fastq_out")
  check_scalar_character(samtools, "samtools")
  check_scalar_character(gzip, "gzip")
  check_scalar_character(conda, "conda")
  check_logical_scalar(overwrite, "overwrite")
  check_logical_scalar(include_unclassified, "include_unclassified")
  check_logical_scalar(allow_empty, "allow_empty")
  check_logical_scalar(dry_run, "dry_run")
  check_logical_scalar(echo, "echo")
  if (!is.null(conda_env)) check_scalar_character(conda_env, "conda_env")

  demux_dir <- normalizePath(demux_dir, mustWork = TRUE)
  conversions <- dorado_bam_to_fastq_plan(
    demux_dir = demux_dir,
    fastq_out = fastq_out,
    include_unclassified = include_unclassified
  )

  if (nrow(conversions) == 0L) {
    stop("No barcode BAM folders found under: ", demux_dir, call. = FALSE)
  }

  existing <- conversions$output_fastq[file.exists(conversions$output_fastq)]
  if (length(existing) > 0L && !isTRUE(overwrite)) {
    stop("Output FASTQ already exists and `overwrite` is FALSE: ", existing[1L],
         call. = FALSE)
  }

  commands <- vapply(
    seq_len(nrow(conversions)),
    function(i) {
      dorado_bam_to_fastq_command(
        bam_files = conversions$bam_files[[i]],
        output_fastq = conversions$output_fastq[[i]],
        samtools = samtools,
        gzip = gzip,
        conda_env = conda_env,
        conda = conda
      )
    },
    character(1)
  )
  names(commands) <- conversions$barcode

  if (isTRUE(echo)) {
    for (command in commands) message(command)
  }

  paths <- list(
    demux_dir = demux_dir,
    bam_pass_dirs = sort(unique(conversions$bam_pass_dir)),
    fastq_dirs = sort(unique(dirname(conversions$output_fastq)))
  )

  if (isTRUE(dry_run)) {
    return(invisible(list(
      status = NA_integer_,
      commands = commands,
      conversions = conversions,
      paths = paths,
      conda_env = conda_env
    )))
  }

  if (is.null(conda_env)) {
    require_external_command(samtools)
  } else {
    require_external_command(conda)
  }
  require_external_command(gzip)

  for (i in seq_len(nrow(conversions))) {
    dir.create(conversions$out_dir[[i]], recursive = TRUE, showWarnings = FALSE)
    conversion_script <- tempfile(fileext = ".sh")
    writeLines(
      c(
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        commands[[i]]
      ),
      conversion_script
    )
    on.exit(unlink(conversion_script), add = TRUE)

    status <- system2(
      "bash",
      args = conversion_script,
      stderr = stderr
    )
    if (!identical(status, 0L)) {
      unlink(conversions$output_fastq[[i]])
      stop("BAM to FASTQ conversion failed with exit status: ", status,
           " for ", conversions$barcode[[i]], call. = FALSE)
    }
    if (!isTRUE(allow_empty) &&
        !dorado_fastq_gz_has_record(conversions$output_fastq[[i]])) {
      unlink(conversions$output_fastq[[i]])
      stop("Converted FASTQ.GZ is empty or invalid for ",
           conversions$barcode[[i]], ": ", conversions$output_fastq[[i]],
           call. = FALSE)
    }
  }

  invisible(list(
    status = 0L,
    commands = commands,
    conversions = conversions,
    paths = paths,
    conda_env = conda_env
  ))
}

dorado_fastq_gz_has_record <- function(path) {
  if (!file.exists(path) || file.info(path)$size == 0) {
    return(FALSE)
  }

  con <- gzfile(path, open = "rt")
  on.exit(close(con), add = TRUE)
  first <- tryCatch(
    readLines(con, n = 1L, warn = FALSE),
    error = function(e) character()
  )
  length(first) > 0L && startsWith(first[[1L]], "@")
}

dorado_custom_barcode_paths <- function(kit_name, barcode_config_dir = NULL) {
  if (!identical(kit_name, "YS-NB576")) {
    return(NULL)
  }

  config_dir <- barcode_config_dir
  if (is.null(config_dir)) {
    env_dir <- Sys.getenv("ONTOOLS_BARCODE_CONFIG_DIR", unset = "")
    if (nzchar(env_dir)) {
      config_dir <- env_dir
    } else {
      config_dir <- system.file("docs", "barcode_configs", package = "ONTools")
    }
  }
  if (!nzchar(config_dir) || !dir.exists(config_dir)) {
    stop("Barcode config directory not found for YS-NB576: ", config_dir,
         call. = FALSE)
  }

  arrangement <- file.path(config_dir, "yisheng_576.toml")
  sequences <- file.path(config_dir, "yisheng_576.fasta")
  if (!file.exists(arrangement)) {
    stop("Barcode arrangement file not found for YS-NB576: ", arrangement,
         call. = FALSE)
  }
  if (!file.exists(sequences)) {
    stop("Barcode sequences file not found for YS-NB576: ", sequences,
         call. = FALSE)
  }

  list(
    arrangement = normalizePath(arrangement, mustWork = TRUE),
    sequences = normalizePath(sequences, mustWork = TRUE)
  )
}

dorado_bam_to_fastq_plan <- function(demux_dir,
                                     fastq_out,
                                     include_unclassified) {
  all_dirs <- list.dirs(demux_dir, recursive = TRUE, full.names = TRUE)
  bam_pass_dirs <- sort(all_dirs[basename(all_dirs) == "bam_pass"])

  rows <- list()
  for (bam_pass_dir in bam_pass_dirs) {
    run_dir <- dirname(bam_pass_dir)
    barcode_dirs <- sort(list.dirs(bam_pass_dir, recursive = TRUE, full.names = TRUE))
    barcode_dirs <- barcode_dirs[barcode_dirs != bam_pass_dir]

    for (barcode_dir in barcode_dirs) {
      bam_files <- sort(list.files(
        barcode_dir,
        pattern = "[.]bam$",
        full.names = TRUE,
        recursive = FALSE
      ))
      if (length(bam_files) == 0L) next

      barcode <- basename(barcode_dir)
      if (!isTRUE(include_unclassified) && identical(barcode, "unclassified")) {
        next
      }

      rel_path <- substring(
        barcode_dir,
        first = nchar(bam_pass_dir) + 2L,
        last = nchar(barcode_dir)
      )
      out_dir <- file.path(run_dir, fastq_out, rel_path)
      output_fastq <- file.path(out_dir, paste0(barcode, ".fastq.gz"))
      rows[[length(rows) + 1L]] <- data.frame(
        bam_pass_dir = bam_pass_dir,
        barcode_dir = barcode_dir,
        barcode = barcode,
        rel_path = rel_path,
        out_dir = out_dir,
        output_fastq = output_fastq,
        n_bam = length(bam_files),
        stringsAsFactors = FALSE
      )
      rows[[length(rows)]]$bam_files <- I(list(bam_files))
    }
  }

  if (length(rows) == 0L) {
    return(data.frame(
      bam_pass_dir = character(),
      barcode_dir = character(),
      barcode = character(),
      rel_path = character(),
      out_dir = character(),
      output_fastq = character(),
      n_bam = integer(),
      bam_files = I(list())
    ))
  }

  do.call(rbind, rows)
}

dorado_bam_to_fastq_command <- function(bam_files,
                                        output_fastq,
                                        samtools,
                                        gzip,
                                        conda_env,
                                        conda) {
  samtools_cmd <- if (is.null(conda_env)) {
    shQuote(samtools)
  } else {
    paste(shQuote(conda), "run", "-n", shQuote(conda_env), shQuote(samtools))
  }
  fastq_commands <- paste(
    samtools_cmd,
    "fastq -n -T '*'",
    shQuote(bam_files)
  )
  paste(
    "set -o pipefail;",
    "{",
    paste(fastq_commands, collapse = "; "),
    "; } |",
    shQuote(gzip),
    "-c >",
    shQuote(output_fastq)
  )
}
