#' Build amplicon variant delivery packages
#'
#' `make_variant_delivery()` runs the ONT amplicon variant-calling delivery
#' workflow: optional Dorado basecalling/demultiplexing, run-level QC, grouping
#' demultiplexed barcode FASTQ folders by sample information, running
#' `wf-amplicon` in reference-based variant-calling mode, generating per-barcode
#' `variant.tsv` files from `medaka.annotated.vcf.gz`, writing a group-level
#' `variant_all.tsv`, optional filtered-read QC, optional IGV snapshots,
#' optional synthetic AB1 chromatograms, and final result collection.
#'
#' @param path_proj MinKNOW project directory.
#' @param path_sampleInfo_file_list Named character vector or list of sample
#'   information CSV files. Names are used as grouped FASTQ folder names.
#' @param reference Reference FASTA file passed to [run_wf_amplicon()] and
#'   used for downstream variant tables, IGV snapshots, and AB1 traces. After
#'   [run_wf_amplicon()] finishes, downstream steps first try to use the
#'   workflow-generated `reference_sanitized_seqID.*` file under each `out_dir`
#'   so reference record names match VCF `CHROM` and BAM contig names.
#' @param path_delivery Root directory where per-group final results are copied.
#' @param kit_name Dorado barcode kit name.
#' @param model Dorado basecalling model or model alias.
#' @param demux_out Demux output directory name under `path_proj`. If `NULL`,
#'   defaults to `demux_out_<kit_name>`.
#' @param fastq_out FASTQ output directory name created by Dorado conversion.
#' @param barcode_both_ends Logical. Passed to [dorado_demux_bam()].
#' @param run_basecalling_demux_step Logical. If `FALSE`, reuse
#'   `work/stat.Rdata` when present or reconstruct output paths from
#'   `path_proj`, `demux_out`, and `fastq_out`.
#' @param run_dorado_basecall_step Logical. Run Dorado basecalling.
#' @param run_dorado_demux_step Logical. Run Dorado barcode demultiplexing.
#' @param run_dorado_fastq_step Logical. Convert demultiplexed BAM files to
#'   FASTQ.GZ files.
#' @param run_QC_step Logical. Generate run-level QC plots and source FASTQ
#'   statistics.
#' @param move_fastq_step Logical. Move barcode FASTQ folders into sample-info
#'   groups before running amplicon analysis.
#' @param move_fastq_mode FASTQ grouping mode: `"move"`, `"reuse"`, or `"auto"`.
#' @param run_amplicon_step Logical. Run [run_wf_amplicon()] for each group.
#' @param make_variant_table_step Logical. Generate per-barcode `variant.tsv`
#'   files and group-level `variant_all.tsv`.
#' @param run_filtered_QC_step Logical. Generate QC plots for filtered reads for
#'   each group.
#' @param run_igv_step Logical. Generate IGV snapshots from
#'   `barcode*/alignments/*.bam` against `reference`.
#' @param make_ab1 Logical. If `TRUE`, create synthetic AB1 chromatogram files
#'   from `barcode*/alignments/*.bam` and `reference`.
#' @param ab1_name_template Output AB1 filename template. `{barcode}` is
#'   replaced by the barcode folder name and `{reference}` is replaced by the
#'   FASTA record name.
#' @param ab1_samtools Command name or full path used by
#'   [synthetic_ab1_from_bam()] to launch `samtools`.
#' @param igv_dir_name Directory name under each barcode folder for IGV
#'   snapshots.
#' @param ab1_dir_name Directory name under each barcode folder for synthetic
#'   AB1 files.
#' @param collect_results_step Logical. Copy final deliverables into
#'   `path_delivery`.
#' @param variant_vcf_name VCF filename under each `barcode*/variants/`
#'   directory.
#' @param variant_tsv_name Per-barcode variant TSV filename to write.
#' @param variant_all_name Group-level merged variant TSV filename to write next
#'   to the `barcode*` directories.
#' @param variant_columns Columns kept in `variant.tsv` and `variant_all.tsv`.
#' @param flank_width Number of reference bases passed to [read_vcf()] for
#'   upstream/downstream sequence extraction.
#' @param project_col,amplicon_size_col,barcode_col Column names in each sample
#'   information file.
#' @param min_read_length_col,max_read_length_col Read-length filter column
#'   names in each sample information file.
#' @param min_read_qual,min_n_reads,force_spoa_length_threshold,override_basecaller_cfg,profile,resume
#'   Parameters passed to [run_wf_amplicon()].
#' @param amplicon_extra_args Optional raw command-line string appended to each
#'   [run_wf_amplicon()] call.
#' @param barcode_digits Number of barcode digits used by [plot_seqQC()] for
#'   filtered-read QC.
#' @param dorado_threads Optional thread count passed to [dorado_demux_bam()].
#' @param dorado_fastq_write_md5 Logical. If `TRUE`, write MD5 checksum files
#'   next to FASTQ.GZ files generated by [dorado_bam_to_fastq()].
#' @param dorado,samtools,gzip Command names or executable paths used by the
#'   split Dorado steps.
#' @param dorado_conda_env Optional conda environment used by the split Dorado,
#'   samtools, and gzip steps.
#' @param conda Conda executable name or path.
#' @param overwrite_fastq Logical. Passed to [move_fastq_to_folders()].
#' @param overwrite_delivery Logical. Replace existing files/directories in the
#'   final delivery directory.
#' @param include_execution Logical. Copy the workflow `execution` directory
#'   when present.
#' @param igv IGV executable path passed to [igv_snapshot()].
#' @param igv_format Snapshot image format passed to [igv_snapshot()].
#' @param igv_sort,igv_display,max_panel_height,use_xvfb IGV rendering options
#'   passed to [igv_snapshot()].
#' @param dry_run Logical. If `TRUE`, build plans and commands without running
#'   external analysis steps or copying final deliverables.
#' @param echo Logical. If `TRUE`, print commands from wrapped command runners.
#' @param wait Logical. Passed to wrapped command runners.
#' @param stdout,stderr Passed to wrapped command runners.
#'
#' @return Invisibly returns a list with run-level QC (`g1`), per-group QC
#'   (`g2`), Dorado/basecalling status (`stat`), FASTQ move plans, amplicon
#'   workflow results, sanitized reference paths used for downstream variant
#'   outputs, variant table summaries, IGV snapshot summaries, synthetic AB1
#'   summaries, delivery copy summaries, and important output paths.
#'
#' @export
make_variant_delivery <- function(path_proj,
                                  path_sampleInfo_file_list,
                                  reference,
                                  path_delivery = "/data/project_delivery",
                                  kit_name = "YS-NB576",
                                  model = "sup",
                                  demux_out = NULL,
                                  fastq_out = "fastq_pass_trim",
                                  barcode_both_ends = FALSE,
                                  run_basecalling_demux_step = TRUE,
                                  run_dorado_basecall_step = run_basecalling_demux_step,
                                  run_dorado_demux_step = run_basecalling_demux_step,
                                  run_dorado_fastq_step = run_basecalling_demux_step,
                                  run_QC_step = TRUE,
                                  move_fastq_step = TRUE,
                                  move_fastq_mode = c("move", "reuse", "auto"),
                                  run_amplicon_step = TRUE,
                                  make_variant_table_step = TRUE,
                                  run_filtered_QC_step = TRUE,
                                  run_igv_step = TRUE,
                                  make_ab1 = TRUE,
                                  ab1_name_template = "{barcode}.{reference}.synthetic.ab1",
                                  ab1_samtools = "samtools",
                                  igv_dir_name = "IGV",
                                  ab1_dir_name = "AB1",
                                  collect_results_step = TRUE,
                                  variant_vcf_name = "medaka.annotated.vcf.gz",
                                  variant_tsv_name = "variant.tsv",
                                  variant_all_name = "variant_all.tsv",
                                  variant_columns = c(
                                    "CHROM",
                                    "reference_name_original",
                                    "reference_name_sanitized",
                                    "POS", "REF", "ALT", "QUAL", "FILTER", "Type",
                                    "ref_depth_downsampled", "alt_depth_downsampled",
                                    "variant_percent", "sampleID",
                                    "ref_upstream_20bp", "ref_downstream_20bp"
                                  ),
                                  flank_width = 20,
                                  project_col = "Project_ID",
                                  amplicon_size_col = "Expected_Size_bp",
                                  barcode_col = "Barcode_ID",
                                  min_read_length_col = "Min_Read_Length",
                                  max_read_length_col = "Max_Read_Length",
                                  min_read_qual = 10,
                                  min_n_reads = 40,
                                  force_spoa_length_threshold = 2000,
                                  override_basecaller_cfg = "dna_r10.4.1_e8.2_400bps_sup@v5.2.0",
                                  profile = "standard",
                                  resume = TRUE,
                                  amplicon_extra_args = NULL,
                                  barcode_digits = 3,
                                  dorado_threads = NULL,
                                  dorado_fastq_write_md5 = TRUE,
                                  dorado = "dorado",
                                  samtools = "samtools",
                                  gzip = "gzip",
                                  dorado_conda_env = NULL,
                                  conda = "conda",
                                  overwrite_fastq = FALSE,
                                  overwrite_delivery = TRUE,
                                  include_execution = FALSE,
                                  igv = "/usr/local/bin/IGV_Linux_2.19.8/igv.sh",
                                  igv_format = "png",
                                  igv_sort = "base",
                                  igv_display = "collapse",
                                  max_panel_height = NULL,
                                  use_xvfb = FALSE,
                                  dry_run = FALSE,
                                  echo = TRUE,
                                  wait = TRUE,
                                  stdout = "",
                                  stderr = "") {
  check_dir_arg(path_proj, "path_proj")
  check_file_arg(reference, "reference")
  check_scalar_character(path_delivery, "path_delivery")
  check_scalar_character(kit_name, "kit_name")
  check_scalar_character(model, "model")
  check_scalar_character(fastq_out, "fastq_out")
  check_scalar_character(variant_vcf_name, "variant_vcf_name")
  check_scalar_character(variant_tsv_name, "variant_tsv_name")
  check_scalar_character(variant_all_name, "variant_all_name")
  if (!is.character(variant_columns) || length(variant_columns) == 0L ||
      anyNA(variant_columns) || any(!nzchar(variant_columns))) {
    stop("`variant_columns` must be a non-empty character vector.", call. = FALSE)
  }
  check_scalar_character(project_col, "project_col")
  check_scalar_character(amplicon_size_col, "amplicon_size_col")
  check_scalar_character(barcode_col, "barcode_col")
  check_scalar_character(min_read_length_col, "min_read_length_col")
  check_scalar_character(max_read_length_col, "max_read_length_col")
  check_scalar_character(override_basecaller_cfg, "override_basecaller_cfg")
  check_scalar_character(profile, "profile")
  check_scalar_character(dorado, "dorado")
  check_scalar_character(samtools, "samtools")
  check_scalar_character(gzip, "gzip")
  check_scalar_character(conda, "conda")
  check_logical_scalar(barcode_both_ends, "barcode_both_ends")
  check_logical_scalar(run_basecalling_demux_step, "run_basecalling_demux_step")
  check_logical_scalar(run_dorado_basecall_step, "run_dorado_basecall_step")
  check_logical_scalar(run_dorado_demux_step, "run_dorado_demux_step")
  check_logical_scalar(run_dorado_fastq_step, "run_dorado_fastq_step")
  check_logical_scalar(run_QC_step, "run_QC_step")
  check_logical_scalar(move_fastq_step, "move_fastq_step")
  move_fastq_mode <- match.arg(move_fastq_mode)
  check_logical_scalar(run_amplicon_step, "run_amplicon_step")
  check_logical_scalar(make_variant_table_step, "make_variant_table_step")
  check_logical_scalar(run_filtered_QC_step, "run_filtered_QC_step")
  check_logical_scalar(run_igv_step, "run_igv_step")
  check_logical_scalar(make_ab1, "make_ab1")
  check_scalar_character(ab1_name_template, "ab1_name_template")
  check_scalar_character(ab1_samtools, "ab1_samtools")
  check_scalar_character(igv_dir_name, "igv_dir_name")
  check_scalar_character(ab1_dir_name, "ab1_dir_name")
  check_logical_scalar(collect_results_step, "collect_results_step")
  check_logical_scalar(resume, "resume")
  check_logical_scalar(overwrite_fastq, "overwrite_fastq")
  check_logical_scalar(overwrite_delivery, "overwrite_delivery")
  check_logical_scalar(include_execution, "include_execution")
  check_scalar_character(igv, "igv")
  igv_format <- match.arg(igv_format, c("png", "pdf", "svg", "jpg", "jpeg"))
  if (!is.null(igv_sort)) {
    check_scalar_character(igv_sort, "igv_sort")
  }
  if (!is.null(igv_display)) {
    igv_display <- match.arg(igv_display, c("collapse", "expand", "squish"))
  }
  if (!is.null(max_panel_height) &&
      (!is.numeric(max_panel_height) || length(max_panel_height) != 1L ||
       is.na(max_panel_height))) {
    stop("`max_panel_height` must be a single numeric value or `NULL`.",
         call. = FALSE)
  }
  check_logical_scalar(use_xvfb, "use_xvfb")
  check_logical_scalar(dry_run, "dry_run")
  check_logical_scalar(echo, "echo")
  check_logical_scalar(wait, "wait")
  if (!is.null(amplicon_extra_args)) {
    check_scalar_character(amplicon_extra_args, "amplicon_extra_args")
  }

  min_n_reads <- validate_positive_integer(min_n_reads, "min_n_reads")
  force_spoa_length_threshold <- validate_positive_integer(
    force_spoa_length_threshold,
    "force_spoa_length_threshold"
  )
  barcode_digits <- validate_positive_integer(barcode_digits, "barcode_digits")
  flank_width <- validate_nonnegative_integer(flank_width, "flank_width")
  min_read_qual <- validate_nonnegative_number(min_read_qual, "min_read_qual")
  dorado_threads <- validate_optional_positive_integer(dorado_threads, "dorado_threads")
  check_logical_scalar(dorado_fastq_write_md5, "dorado_fastq_write_md5")
  if (!is.null(dorado_conda_env)) {
    check_scalar_character(dorado_conda_env, "dorado_conda_env")
  }
  if (!is.null(demux_out)) {
    check_scalar_character(demux_out, "demux_out")
  }
  if (isTRUE(make_ab1) && !grepl("[{]barcode[}]", ab1_name_template)) {
    stop("`ab1_name_template` must contain `{barcode}`.", call. = FALSE)
  }

  path_proj <- normalizePath(path_proj, mustWork = TRUE)
  reference <- normalizePath(reference, mustWork = TRUE)
  path_sampleInfo_file_list <- validate_sample_info_file_list(
    path_sampleInfo_file_list
  )
  demux_out_name <- if (is.null(demux_out)) paste0("demux_out_", kit_name) else demux_out

  path_work <- file.path(path_proj, "work")
  dir.create(path_work, showWarnings = FALSE, recursive = TRUE)
  dir.create(path_delivery, showWarnings = FALSE, recursive = TRUE)
  if (dir.exists(path_delivery)) {
    path_delivery <- normalizePath(path_delivery, mustWork = TRUE)
  } else if (isTRUE(dry_run)) {
    path_delivery <- normalizePath(path_delivery, mustWork = FALSE)
  } else {
    stop("Could not create `path_delivery`: ", path_delivery, call. = FALSE)
  }

  stat <- run_variant_dorado_steps(
    path_proj = path_proj,
    path_work = path_work,
    kit_name = kit_name,
    model = model,
    demux_out_name = demux_out_name,
    fastq_out = fastq_out,
    barcode_both_ends = barcode_both_ends,
    run_dorado_basecall_step = run_dorado_basecall_step,
    run_dorado_demux_step = run_dorado_demux_step,
    run_dorado_fastq_step = run_dorado_fastq_step,
    dorado_threads = dorado_threads,
    dorado_fastq_write_md5 = dorado_fastq_write_md5,
    dorado = dorado,
    samtools = samtools,
    gzip = gzip,
    dorado_conda_env = dorado_conda_env,
    conda = conda,
    dry_run = dry_run,
    echo = echo,
    wait = wait,
    stderr = stderr
  )

  if (!isTRUE(run_dorado_basecall_step) &&
      !isTRUE(run_dorado_demux_step) &&
      !isTRUE(run_dorado_fastq_step)) {
    message("Step 1: Dorado basecalling, demultiplexing, and FASTQ conversion (skipped)")
    stat_file <- file.path(path_work, "stat.Rdata")
    if (file.exists(stat_file)) {
      load(stat_file)
    } else {
      stat <- list(
        command = NA_character_,
        args = character(),
        status = NA_integer_,
        paths = dorado_demux_to_fastq_paths(
          proj = path_proj,
          model = model,
          demux_out = demux_out_name,
          fastq_out = fastq_out,
          scan_dynamic = TRUE
        )
      )
    }
  }

  fastq_root <- select_single_path(
    stat$paths$fastq_dirs,
    "FASTQ output directory",
    fallback = if (isTRUE(dry_run)) file.path(stat$paths$demux_dir, "<run_dir>", fastq_out) else NA_character_
  )
  run_root <- select_single_path(
    stat$paths$run_dirs,
    "Dorado run directory",
    fallback = if (isTRUE(dry_run)) file.path(stat$paths$demux_dir, "<run_dir>") else NA_character_
  )
  path_seq_summary <- file.path(stat$paths$demux_dir, "sequencing_summary.txt")
  message("Sequencing summary is saved here: ", path_seq_summary)

  fig_path <- file.path(stat$paths$demux_dir, "figs", "png")
  stat_path <- file.path(stat$paths$demux_dir, "stats")
  dir.create(fig_path, showWarnings = FALSE, recursive = TRUE)
  dir.create(stat_path, showWarnings = FALSE, recursive = TRUE)

  g1 <- NULL
  source_fastq_stats <- NULL
  if (isTRUE(run_QC_step)) {
    qc <- run_variant_source_qc(
      path_seq_summary = path_seq_summary,
      fastq_root = fastq_root,
      model = model,
      fig_path = fig_path,
      stat_path = stat_path,
      dry_run = dry_run
    )
    g1 <- qc$plot
    source_fastq_stats <- qc$source_fastq_stats
  } else {
    message("Step 2: Making QC plots for all samples (skipped)")
  }

  move_plans <- list()
  workflow <- list()
  variant_tables <- list()
  variant_references <- list()
  g2 <- list()
  igv_results <- list()
  ab1_results <- list()
  delivery <- list()

  for (folder in names(path_sampleInfo_file_list)) {
    message(folder)
    sample_info_file <- path_sampleInfo_file_list[[folder]]
    sample_info <- read_sample_info_table(sample_info_file)
    sample_barcode_col <- resolve_barcode_col(sample_info, barcode_col)
    validate_amplicon_delivery_sample_info(
      sample_info = sample_info,
      required_cols = c(sample_barcode_col, min_read_length_col, max_read_length_col)
    )
    sample_info_sub <- sample_info[1, , drop = FALSE]
    min_read_length <- validate_positive_integer(
      sample_info_sub[[min_read_length_col]],
      min_read_length_col
    )
    max_read_length <- validate_positive_integer(
      sample_info_sub[[max_read_length_col]],
      max_read_length_col
    )
    if (min_read_length > max_read_length) {
      stop("`", min_read_length_col, "` must be less than or equal to `",
           max_read_length_col, "` for group `", folder, "`.", call. = FALSE)
    }

    if (isTRUE(move_fastq_step)) {
      if (is.na(fastq_root)) {
        stop("No FASTQ output directory was found for moving barcode folders.",
             call. = FALSE)
      }
      message("Step 3: Prepare fastq files in group folder")
      reuse_plan <- make_fastq_reuse_plan(
        fastq_dir = fastq_root,
        group = folder,
        sample_info = sample_info,
        barcode_col = sample_barcode_col
      )
      can_reuse_fastq <- all(reuse_plan$destination_exists)

      if (identical(move_fastq_mode, "reuse")) {
        if (!can_reuse_fastq && !isTRUE(dry_run)) {
          stop(
            "Grouped FASTQ folder is incomplete for `", folder, "`. Missing: ",
            paste(reuse_plan$destination[!reuse_plan$destination_exists], collapse = ", "),
            call. = FALSE
          )
        }
        move_plans[[folder]] <- reuse_plan
      } else if (identical(move_fastq_mode, "auto") && can_reuse_fastq) {
        message("Step 3: Reusing existing grouped FASTQ folder for ", folder)
        move_plans[[folder]] <- reuse_plan
      } else if (isTRUE(dry_run) && !dir.exists(fastq_root)) {
        move_plans[[folder]] <- make_fastq_move_plan_without_source_dir(
          fastq_dir = fastq_root,
          sample_info = sample_info,
          project_col = project_col,
          amplicon_size_col = amplicon_size_col,
          barcode_col = sample_barcode_col
        )
      } else {
        move_plans[[folder]] <- move_fastq_to_folders(
          fastq_dir = fastq_root,
          sample_info = sample_info_file,
          project_col = project_col,
          amplicon_size_col = amplicon_size_col,
          barcode_col = barcode_col,
          overwrite = overwrite_fastq,
          dry_run = dry_run
        )
      }
    } else {
      message("Step 3: Move fastq files to a folder (skipped)")
      move_plans[[folder]] <- NULL
    }

    group_fastq <- if (is.na(fastq_root)) NA_character_ else file.path(fastq_root, folder)
    group_out_dir <- if (is.na(run_root)) {
      file.path(stat$paths$demux_dir, "results", "wf_amplicon_variant", folder)
    } else {
      file.path(run_root, "results", "wf_amplicon_variant", folder)
    }

    if (isTRUE(run_amplicon_step)) {
      message("Step 4: Run amplicon variant workflow")
      workflow[[folder]] <- run_wf_amplicon(
        fastq = group_fastq,
        out_dir = group_out_dir,
        reference = reference,
        min_read_length = min_read_length,
        max_read_length = max_read_length,
        min_read_qual = min_read_qual,
        min_n_reads = min_n_reads,
        force_spoa_length_threshold = force_spoa_length_threshold,
        override_basecaller_cfg = override_basecaller_cfg,
        profile = profile,
        resume = resume,
        extra_args = amplicon_extra_args,
        dry_run = dry_run,
        echo = echo,
        wait = wait,
        stdout = stdout,
        stderr = stderr
      )
    } else {
      message("Step 4: Run amplicon variant workflow (skipped)")
      workflow[[folder]] <- list(
        status = NA_integer_,
        paths = list(fastq = group_fastq, out_dir = group_out_dir, reference = reference)
      )
    }
    variant_reference <- resolve_wf_amplicon_variant_reference(
      result_dir = workflow[[folder]]$paths$out_dir,
      reference = reference,
      dry_run = dry_run
    )
    variant_references[[folder]] <- variant_reference

    if (isTRUE(make_variant_table_step)) {
      message("Step 5: Generate variant tables")
      variant_tables[[folder]] <- make_wf_amplicon_variant_tables(
        result_dir = workflow[[folder]]$paths$out_dir,
        reference = variant_reference,
        original_reference = reference,
        variant_vcf_name = variant_vcf_name,
        variant_tsv_name = variant_tsv_name,
        variant_all_name = variant_all_name,
        variant_columns = variant_columns,
        flank_width = flank_width,
        dry_run = dry_run
      )
    } else {
      message("Step 5: Generate variant tables (skipped)")
      variant_tables[[folder]] <- NULL
    }

    if (isTRUE(run_filtered_QC_step)) {
      if (!file.exists(path_seq_summary)) {
        if (isTRUE(dry_run)) {
          message("Step 6: Run QC plots for filtered reads (dry-run; sequencing summary not found)")
          g2[[folder]] <- NULL
        } else {
          stop("Sequencing summary file not found: ", path_seq_summary, call. = FALSE)
        }
      } else {
        message("Step 6: Run QC plots for filtered reads")
        barcode_numbers <- barcode_ids_to_numbers(sample_info[[sample_barcode_col]])
        g2[[folder]] <- plot_seqQC(
          filePath = path_seq_summary,
          runName = model,
          device = "png",
          barcodes = barcode_numbers,
          barcode_digits = barcode_digits,
          min_read_length = min_read_length,
          max_read_length = max_read_length,
          filename_suffix = "_filtered",
          sample_len_dir_mode = "fastq_pass_trim",
          fastq_pass_trim_dir = workflow[[folder]]$paths$fastq,
          plot_unclassified = FALSE
        )

        ggplot2::ggsave(
          filename = file.path(workflow[[folder]]$paths$out_dir, "numRead_perSample.png"),
          plot = g2[[folder]]$numRead,
          width = 12,
          height = 8
        )
        ggplot2::ggsave(
          filename = file.path(workflow[[folder]]$paths$out_dir, "lenReadDistribution.png"),
          plot = g2[[folder]]$lenRead,
          width = 15,
          height = 15
        )
        utils::write.csv(
          g2[[folder]]$read_counts,
          file = file.path(workflow[[folder]]$paths$out_dir, "numRead_perSample.csv")
        )
      }
    } else {
      message("Step 6: Run QC plots for filtered reads (skipped)")
      g2[[folder]] <- NULL
    }

    if (isTRUE(run_igv_step)) {
      message("Step 7: Generate IGV plots")
      igv_results[[folder]] <- generate_variant_igv_snapshots(
        result_dir = workflow[[folder]]$paths$out_dir,
        reference = variant_reference,
        barcode_pattern = "^barcode[0-9]+$",
        format = igv_format,
        igv = igv,
        sort = igv_sort,
        display = igv_display,
        max_panel_height = max_panel_height,
        use_xvfb = use_xvfb,
        igv_dir_name = igv_dir_name,
        dry_run = dry_run
      )
    } else {
      message("Step 7: Generate IGV plots (skipped)")
      igv_results[[folder]] <- NULL
    }

    if (isTRUE(make_ab1)) {
      message("Step 8: Generate synthetic AB1 files")
      ab1_results[[folder]] <- generate_variant_ab1_files(
        result_dir = workflow[[folder]]$paths$out_dir,
        reference = variant_reference,
        barcode_pattern = "^barcode[0-9]+$",
        ab1_name_template = ab1_name_template,
        ab1_dir_name = ab1_dir_name,
        samtools = ab1_samtools,
        overwrite = overwrite_delivery,
        dry_run = dry_run,
        echo = echo,
        stderr = stderr
      )
    } else {
      message("Step 8: Generate synthetic AB1 files (skipped)")
      ab1_results[[folder]] <- NULL
    }

    if (isTRUE(collect_results_step)) {
      message("Step 9: Deliver the results")
      output_dir <- file.path(path_delivery, folder, "variant_results")
      if (isTRUE(dry_run)) {
        delivery[[folder]] <- data.frame(
          label = "delivery",
          source = workflow[[folder]]$paths$out_dir,
          destination = output_dir,
          type = "directory",
          exists = dir.exists(workflow[[folder]]$paths$out_dir),
          copied = FALSE,
          stringsAsFactors = FALSE
        )
      } else {
        delivery[[folder]] <- collect_variant_results(
          result_dir = workflow[[folder]]$paths$out_dir,
          output_dir = output_dir,
          sample_map = sample_info_file,
          variant_all_name = variant_all_name,
          barcode_pattern = "^barcode[0-9]+$",
          fastq_pass_trim_dir = workflow[[folder]]$paths$fastq,
          include_execution = include_execution,
          include_igv = run_igv_step,
          include_ab1 = make_ab1,
          ab1_name_template = ab1_name_template,
          igv_dir_name = igv_dir_name,
          ab1_dir_name = ab1_dir_name,
          overwrite = overwrite_delivery
        )
        utils::write.csv(
          delivery[[folder]],
          file = file.path(path_work, paste0("variant_delivery_stats_", folder, ".csv")),
          row.names = FALSE
        )
      }
    } else {
      message("Step 9: Deliver the results (skipped)")
      delivery[[folder]] <- NULL
    }
  }

  invisible(list(
    g1 = g1,
    g2 = g2,
    stat = stat,
    move_plans = move_plans,
    workflow = workflow,
    variant_tables = variant_tables,
    variant_references = variant_references,
    igv = igv_results,
    ab1 = ab1_results,
    delivery = delivery,
    source_fastq_stats = source_fastq_stats,
    reference = reference,
    path_work = path_work,
    path_delivery = path_delivery,
    path_seq_summary = path_seq_summary,
    fig_path = fig_path,
    stat_path = stat_path
  ))
}

run_variant_dorado_steps <- function(path_proj,
                                     path_work,
                                     kit_name,
                                     model,
                                     demux_out_name,
                                     fastq_out,
                                     barcode_both_ends,
                                     run_dorado_basecall_step,
                                     run_dorado_demux_step,
                                     run_dorado_fastq_step,
                                     dorado_threads,
                                     dorado_fastq_write_md5,
                                     dorado,
                                     samtools,
                                     gzip,
                                     dorado_conda_env,
                                     conda,
                                     dry_run,
                                     echo,
                                     wait,
                                     stderr) {
  if (!isTRUE(run_dorado_basecall_step) &&
      !isTRUE(run_dorado_demux_step) &&
      !isTRUE(run_dorado_fastq_step)) {
    return(NULL)
  }

  calls_bam <- file.path(path_proj, "bam", paste0("calls_", model, ".bam"))
  demux_dir <- file.path(path_proj, demux_out_name)

  if (isTRUE(run_dorado_basecall_step)) {
    message("Step 1a: Dorado basecalling")
    basecall_stat <- dorado_basecall(
      proj = path_proj,
      model = model,
      output_bam = calls_bam,
      overwrite = TRUE,
      dorado = dorado,
      conda_env = dorado_conda_env,
      conda = conda,
      dry_run = dry_run,
      echo = echo,
      stderr = stderr
    )
  } else {
    message("Step 1a: Dorado basecalling (skipped)")
    basecall_stat <- list(
      status = NA_integer_,
      command = NA_character_,
      args = character(),
      command_string = NA_character_,
      paths = list(
        project_dir = path_proj,
        pod5_dir = file.path(path_proj, "pod5"),
        output_bam = calls_bam
      ),
      conda_env = dorado_conda_env
    )
  }

  if (isTRUE(run_dorado_demux_step)) {
    message("Step 1b: Dorado barcode demultiplexing")
    demux_stat <- dorado_demux_bam(
      calls_bam = calls_bam,
      demux_dir = demux_dir,
      kit_name = kit_name,
      barcode_both_ends = barcode_both_ends,
      emit_summary = TRUE,
      threads = dorado_threads,
      require_bam_pass = !isTRUE(dry_run),
      dorado = dorado,
      conda_env = dorado_conda_env,
      conda = conda,
      dry_run = dry_run,
      echo = echo,
      stderr = stderr
    )
  } else {
    message("Step 1b: Dorado barcode demultiplexing (skipped)")
    demux_stat <- list(
      status = NA_integer_,
      command = NA_character_,
      args = character(),
      command_string = NA_character_,
      paths = list(calls_bam = calls_bam, demux_dir = demux_dir),
      conda_env = dorado_conda_env
    )
  }

  if (isTRUE(run_dorado_fastq_step)) {
    message("Step 1c: Convert demultiplexed BAM files to FASTQ.GZ")
    if (isTRUE(dry_run) && !dorado_demux_has_bam_pass(demux_dir)) {
      fastq_stat <- list(
        status = NA_integer_,
        commands = character(),
        conversions = data.frame(
          bam_pass_dir = character(),
          barcode_dir = character(),
          barcode = character(),
          rel_path = character(),
          out_dir = character(),
          output_fastq = character(),
          n_bam = integer(),
          bam_files = I(list())
        ),
        paths = list(
          demux_dir = demux_dir,
          bam_pass_dirs = character(),
          fastq_dirs = character()
        ),
        conda_env = dorado_conda_env,
        note = "dry_run: no bam_pass directory exists yet, so FASTQ conversion commands could not be enumerated."
      )
    } else {
      fastq_stat <- dorado_bam_to_fastq(
        demux_dir = demux_dir,
        fastq_out = fastq_out,
        overwrite = TRUE,
        include_unclassified = TRUE,
        allow_empty = FALSE,
        write_md5 = dorado_fastq_write_md5,
        samtools = samtools,
        gzip = gzip,
        conda_env = dorado_conda_env,
        conda = conda,
        dry_run = dry_run,
        echo = echo,
        stderr = stderr
      )
    }
  } else {
    message("Step 1c: Convert demultiplexed BAM files to FASTQ.GZ (skipped)")
    fastq_stat <- list(
      status = NA_integer_,
      commands = character(),
      conversions = data.frame(),
      paths = list(demux_dir = demux_dir, bam_pass_dirs = character(), fastq_dirs = character()),
      conda_env = dorado_conda_env
    )
  }

  stat <- make_consensus_dorado_stat(
    proj = path_proj,
    model = model,
    demux_out = demux_out_name,
    fastq_out = fastq_out,
    basecall = basecall_stat,
    demux = demux_stat,
    fastq = fastq_stat
  )
  if (!isTRUE(dry_run) && isTRUE(wait)) {
    save(stat, file = file.path(path_work, "stat.Rdata"))
  }
  stat
}

run_variant_source_qc <- function(path_seq_summary,
                                  fastq_root,
                                  model,
                                  fig_path,
                                  stat_path,
                                  dry_run) {
  if (!file.exists(path_seq_summary)) {
    if (isTRUE(dry_run)) {
      message("Step 2: Making QC plots for all samples (dry-run; sequencing summary not found)")
      return(list(plot = NULL, source_fastq_stats = NULL))
    }
    stop("Sequencing summary file not found: ", path_seq_summary, call. = FALSE)
  }
  if (is.na(fastq_root)) {
    stop("No FASTQ output directory was found for run-level QC.", call. = FALSE)
  }

  message("Step 2: Making QC plots for all samples")
  g1 <- plot_seqQC(
    filePath = path_seq_summary,
    runName = model,
    device = "png",
    barcodes = NULL,
    sample_len_dir_mode = "fastq_pass_trim",
    fastq_pass_trim_dir = fastq_root
  )
  message("Demultiplexing rate is ", g1$recovery)

  ggplot2::ggsave(
    filename = file.path(fig_path, "numRead_perSample.png"),
    plot = g1$numRead,
    width = 16,
    height = 8
  )
  ggplot2::ggsave(
    filename = file.path(fig_path, "lenReadDistribution.png"),
    plot = g1$lenRead,
    width = 22,
    height = 22
  )
  utils::write.csv(g1$read_counts, file = file.path(stat_path, "numRead_perSample.csv"))

  source_fastqs <- list.files(
    file.path(fastq_root, list.files(fastq_root)),
    pattern = "[.]fastq[.]gz$",
    full.names = TRUE
  )
  source_fastq_stats <- fastq_stats(
    fastq = source_fastqs,
    stderr = FALSE,
    echo = FALSE,
    conda_env = NULL
  )$stats
  utils::write.csv(source_fastq_stats, file = file.path(stat_path, "stat_source_fastq.csv"))

  list(plot = g1, source_fastq_stats = source_fastq_stats)
}

make_wf_amplicon_variant_tables <- function(result_dir,
                                            reference,
                                            original_reference = reference,
                                            variant_vcf_name,
                                            variant_tsv_name,
                                            variant_all_name,
                                            variant_columns,
                                            flank_width,
                                            dry_run) {
  result_dir_exists <- dir.exists(result_dir)
  barcode_dirs <- if (result_dir_exists) {
    list.dirs(result_dir, recursive = FALSE, full.names = TRUE)
  } else {
    character()
  }
  barcode_dirs <- barcode_dirs[grepl("^barcode[0-9]+$", basename(barcode_dirs))]
  barcode_dirs <- sort(barcode_dirs)
  reference_map <- make_variant_reference_name_map(
    original_reference = original_reference,
    sanitized_reference = reference
  )

  rows <- data.frame(
    barcode = basename(barcode_dirs),
    vcf = file.path(barcode_dirs, "variants", variant_vcf_name),
    variant_tsv = file.path(barcode_dirs, variant_tsv_name),
    exists = file.exists(file.path(barcode_dirs, "variants", variant_vcf_name)),
    n_variants = rep(NA_integer_, length(barcode_dirs)),
    status = rep(if (isTRUE(dry_run)) "dry_run" else "pending", length(barcode_dirs)),
    stringsAsFactors = FALSE
  )
  all_path <- file.path(result_dir, variant_all_name)

  if (isTRUE(dry_run)) {
    return(list(
      result_dir = result_dir,
      variant_all = all_path,
      files = rows,
      status = "dry_run"
    ))
  }
  if (!result_dir_exists) {
    stop("`result_dir` does not exist: ", result_dir, call. = FALSE)
  }
  if (length(barcode_dirs) == 0L) {
    warning("No barcode directories found under: ", result_dir, call. = FALSE)
    variant_all <- empty_variant_table(variant_columns)
    utils::write.table(
      variant_all,
      file = all_path,
      sep = "\t",
      quote = FALSE,
      row.names = FALSE
    )
    return(list(
      result_dir = result_dir,
      variant_all = all_path,
      files = rows,
      status = "no_barcodes"
    ))
  }

  variant_list <- list()
  for (i in seq_along(barcode_dirs)) {
    barcode_dir <- barcode_dirs[[i]]
    barcode <- basename(barcode_dir)
    vcf <- file.path(barcode_dir, "variants", variant_vcf_name)
    out_tsv <- file.path(barcode_dir, variant_tsv_name)

    if (!file.exists(vcf)) {
      rows$status[[i]] <- "missing_vcf"
      warning("Variant VCF not found for `", barcode, "`: ", vcf, call. = FALSE)
      next
    }

    variant <- read_vcf(
      vcf_file = vcf,
      reference_fasta = reference,
      flank_width = flank_width
    )
    if (is.null(variant)) {
      variant <- empty_variant_table(variant_columns)
      rows$status[[i]] <- "no_variants"
    } else {
      variant <- add_variant_reference_name_columns(variant, reference_map)
      variant <- subset_variant_columns(variant, variant_columns)
      rows$status[[i]] <- "written"
    }
    rows$n_variants[[i]] <- nrow(variant)

    utils::write.table(
      variant,
      file = out_tsv,
      sep = "\t",
      quote = FALSE,
      row.names = FALSE
    )
    rows$variant_tsv[[i]] <- normalizePath(out_tsv, mustWork = TRUE)
    variant_list[[barcode]] <- variant
  }

  variant_all <- if (length(variant_list) == 0L) {
    empty_variant_table(variant_columns)
  } else {
    do.call(rbind, unname(variant_list))
  }
  rownames(variant_all) <- NULL
  utils::write.table(
    variant_all,
    file = all_path,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  list(
    result_dir = result_dir,
    variant_all = normalizePath(all_path, mustWork = TRUE),
    files = rows,
    status = "written"
  )
}

subset_variant_columns <- function(variant, variant_columns) {
  missing_cols <- setdiff(variant_columns, names(variant))
  for (col in missing_cols) {
    variant[[col]] <- NA
  }
  variant[, variant_columns, drop = FALSE]
}

empty_variant_table <- function(variant_columns) {
  as.data.frame(
    stats::setNames(rep(list(logical()), length(variant_columns)), variant_columns),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

make_variant_reference_name_map <- function(original_reference, sanitized_reference) {
  check_file_arg(original_reference, "original_reference")
  check_file_arg(sanitized_reference, "sanitized_reference")
  original <- Biostrings::readDNAStringSet(original_reference)
  sanitized <- Biostrings::readDNAStringSet(sanitized_reference)
  original_names <- names(original)
  sanitized_names <- names(sanitized)
  if (is.null(original_names) || any(!nzchar(original_names))) {
    stop("All FASTA records in `original_reference` must have names.",
         call. = FALSE)
  }
  if (is.null(sanitized_names) || any(!nzchar(sanitized_names))) {
    stop("All FASTA records in `sanitized_reference` must have names.",
         call. = FALSE)
  }
  if (length(original) != length(sanitized)) {
    warning(
      "`original_reference` and `sanitized_reference` contain different numbers of records; ",
      "reference name mapping may be incomplete.",
      call. = FALSE
    )
  }

  n <- min(length(original), length(sanitized))
  if (n == 0L) {
    return(data.frame(
      reference_name_sanitized = character(),
      reference_name_original = character(),
      stringsAsFactors = FALSE
    ))
  }

  data.frame(
    reference_name_sanitized = sanitized_names[seq_len(n)],
    reference_name_original = original_names[seq_len(n)],
    stringsAsFactors = FALSE
  )
}

add_variant_reference_name_columns <- function(variant, reference_map) {
  variant$reference_name_sanitized <- variant$CHROM
  variant$reference_name_original <- variant$CHROM
  if (nrow(reference_map) == 0L || !"CHROM" %in% names(variant)) {
    return(variant)
  }

  idx <- match(variant$CHROM, reference_map$reference_name_sanitized)
  matched <- !is.na(idx)
  variant$reference_name_original[matched] <- reference_map$reference_name_original[idx[matched]]
  variant
}

resolve_wf_amplicon_variant_reference <- function(result_dir, reference, dry_run) {
  check_file_arg(reference, "reference")
  reference <- normalizePath(reference, mustWork = TRUE)
  if (isTRUE(dry_run) || !dir.exists(result_dir)) {
    return(reference)
  }

  direct_candidates <- list.files(
    result_dir,
    pattern = "^reference_sanitized_seqID[.](fa|fasta|fq|fastq)([.]gz)?$",
    full.names = TRUE,
    ignore.case = TRUE
  )
  candidates <- direct_candidates
  if (length(candidates) == 0L) {
    candidates <- list.files(
      result_dir,
      pattern = "^reference_sanitized_seqID[.](fa|fasta|fq|fastq)([.]gz)?$",
      full.names = TRUE,
      recursive = TRUE,
      ignore.case = TRUE
    )
  }
  candidates <- sort(candidates[file.exists(candidates)])

  if (length(candidates) > 0L) {
    if (length(candidates) > 1L) {
      warning(
        "Multiple sanitized reference files were found under `result_dir`; using the first: ",
        candidates[[1]],
        call. = FALSE
      )
    }
    return(normalizePath(candidates[[1]], mustWork = TRUE))
  }

  original_names <- names(Biostrings::readDNAStringSet(reference))
  if (length(original_names) > 0L &&
      any(grepl("[[:space:]]", original_names))) {
    warning(
      "No `reference_sanitized_seqID.*` file was found under `result_dir`, ",
      "but the original reference contains whitespace in sequence names. ",
      "Variant table/IGV/AB1 generation may fail if VCF/BAM sequence names were sanitized by wf-amplicon.",
      call. = FALSE
    )
  }

  reference
}

generate_variant_igv_snapshots <- function(result_dir,
                                           reference,
                                           barcode_pattern,
                                           format,
                                           igv,
                                           sort,
                                           display,
                                           max_panel_height,
                                           use_xvfb,
                                           igv_dir_name,
                                           dry_run) {
  check_file_arg(reference, "reference")
  reference <- normalizePath(reference, mustWork = TRUE)
  ref_names <- variant_reference_names(reference)
  barcode_dirs <- variant_barcode_dirs(result_dir, barcode_pattern)

  rows <- data.frame(
    barcode = character(),
    reference_name = character(),
    bam = character(),
    bai = character(),
    snapshot = character(),
    bam_exists = logical(),
    bai_exists = logical(),
    generated = logical(),
    status = character(),
    stringsAsFactors = FALSE
  )
  details <- list()

  for (barcode_dir in barcode_dirs) {
    barcode <- basename(barcode_dir)
    bam <- file.path(barcode_dir, "alignments", paste0(barcode, ".aligned.sorted.bam"))
    bai <- delivery_standard_bam_index_path(bam)
    bam_exists <- file.exists(bam)
    bai_exists <- !is.na(bai)
    igv_dir <- file.path(barcode_dir, igv_dir_name)

    for (ref_name in ref_names) {
      snapshot_name <- paste0(
        barcode,
        ".",
        sanitize_igv_snapshot_name(ref_name),
        ".",
        format
      )
      snapshot <- file.path(igv_dir, snapshot_name)

      if (isTRUE(dry_run)) {
        rows <- rbind(rows, data.frame(
          barcode = barcode,
          reference_name = ref_name,
          bam = bam,
          bai = if (is.na(bai)) paste0(bam, ".bai") else bai,
          snapshot = snapshot,
          bam_exists = bam_exists,
          bai_exists = bai_exists,
          generated = FALSE,
          status = "dry_run",
          stringsAsFactors = FALSE
        ))
        next
      }

      if (!bam_exists) {
        stop("BAM file not found for `", barcode, "`: ", bam, call. = FALSE)
      }
      if (!bai_exists) {
        stop("BAM index not found for `", barcode, "`: ", paste0(bam, ".bai"),
             call. = FALSE)
      }

      res <- igv_snapshot(
        genome_fasta = reference,
        bam = bam,
        chr = ref_name,
        out_dir = igv_dir,
        format = format,
        snapshot_name = snapshot_name,
        igv = igv,
        sort = sort,
        display = display,
        max_panel_height = max_panel_height,
        use_xvfb = use_xvfb
      )
      key <- paste(barcode, ref_name, sep = ":")
      details[[key]] <- res

      rows <- rbind(rows, data.frame(
        barcode = barcode,
        reference_name = ref_name,
        bam = bam,
        bai = bai,
        snapshot = normalizePath(snapshot, mustWork = file.exists(snapshot)),
        bam_exists = bam_exists,
        bai_exists = bai_exists,
        generated = identical(res$status, 0L),
        status = if (identical(res$status, 0L)) "generated" else paste0("status_", res$status),
        stringsAsFactors = FALSE
      ))
    }
  }

  list(files = rows, details = details)
}

generate_variant_ab1_files <- function(result_dir,
                                       reference,
                                       barcode_pattern,
                                       ab1_name_template,
                                       ab1_dir_name,
                                       samtools,
                                       overwrite,
                                       dry_run,
                                       echo,
                                       stderr) {
  if (!grepl("[{]barcode[}]", ab1_name_template)) {
    stop("`ab1_name_template` must contain `{barcode}`.", call. = FALSE)
  }

  check_file_arg(reference, "reference")
  reference <- normalizePath(reference, mustWork = TRUE)
  ref_names <- variant_reference_names(reference)
  barcode_dirs <- variant_barcode_dirs(result_dir, barcode_pattern)

  rows <- data.frame(
    barcode = character(),
    reference_name = character(),
    reference = character(),
    bam = character(),
    bai = character(),
    ab1 = character(),
    reference_exists = logical(),
    bam_exists = logical(),
    bai_exists = logical(),
    generated = logical(),
    status = character(),
    stringsAsFactors = FALSE
  )

  for (barcode_dir in barcode_dirs) {
    barcode <- basename(barcode_dir)
    bam <- file.path(barcode_dir, "alignments", paste0(barcode, ".aligned.sorted.bam"))
    bai <- delivery_standard_bam_index_path(bam)
    bam_exists <- file.exists(bam)
    bai_exists <- !is.na(bai)
    ab1_dir <- file.path(barcode_dir, ab1_dir_name)

    for (ref_name in ref_names) {
      ab1_name <- sub("[{]barcode[}]", barcode, ab1_name_template)
      ab1_name <- sub("[{]reference[}]", sanitize_igv_snapshot_name(ref_name), ab1_name)
      ab1 <- file.path(ab1_dir, ab1_name)

      if (isTRUE(dry_run)) {
        rows <- rbind(rows, data.frame(
          barcode = barcode,
          reference_name = ref_name,
          reference = reference,
          bam = bam,
          bai = if (is.na(bai)) paste0(bam, ".bai") else bai,
          ab1 = ab1,
          reference_exists = file.exists(reference),
          bam_exists = bam_exists,
          bai_exists = bai_exists,
          generated = FALSE,
          status = "dry_run",
          stringsAsFactors = FALSE
        ))
        next
      }

      if (!bam_exists) {
        stop("BAM file not found for `", barcode, "`: ", bam, call. = FALSE)
      }
      if (!bai_exists) {
        stop("BAM index not found for `", barcode, "`: ", paste0(bam, ".bai"),
             call. = FALSE)
      }

      synthetic_ab1_from_bam(
        consensus = reference,
        bam = bam,
        output_ab1 = ab1,
        reference_name = ref_name,
        sample = paste(barcode, ref_name, sep = "_"),
        samtools = samtools,
        overwrite = overwrite,
        echo = echo,
        stderr = stderr
      )

      rows <- rbind(rows, data.frame(
        barcode = barcode,
        reference_name = ref_name,
        reference = reference,
        bam = bam,
        bai = bai,
        ab1 = normalizePath(ab1, mustWork = TRUE),
        reference_exists = file.exists(reference),
        bam_exists = bam_exists,
        bai_exists = bai_exists,
        generated = TRUE,
        status = "generated",
        stringsAsFactors = FALSE
      ))
    }
  }

  rows
}

variant_barcode_dirs <- function(result_dir, barcode_pattern) {
  barcode_dirs <- if (dir.exists(result_dir)) {
    list.dirs(result_dir, recursive = FALSE, full.names = TRUE)
  } else {
    character()
  }
  barcode_dirs <- barcode_dirs[grepl(barcode_pattern, basename(barcode_dirs))]
  sort(barcode_dirs)
}

variant_reference_names <- function(reference) {
  records <- Biostrings::readDNAStringSet(reference)
  if (length(records) == 0L) {
    stop("No FASTA records found in `reference`.", call. = FALSE)
  }
  ref_names <- names(records)
  if (is.null(ref_names) || any(!nzchar(ref_names))) {
    stop("All FASTA records in `reference` must have names.", call. = FALSE)
  }
  ref_names
}

collect_variant_results <- function(result_dir,
                                    output_dir,
                                    sample_map = NULL,
                                    variant_all_name = "variant_all.tsv",
                                    barcode_pattern = "^barcode[0-9]+$",
                                    fastq_pass_trim_dir = NULL,
                                    sample_length_plot_pattern = "^Distribution_seqLength__.*\\.png$",
                                    include_execution = FALSE,
                                    include_igv = FALSE,
                                    include_ab1 = FALSE,
                                    ab1_name_template = "{barcode}.{reference}.synthetic.ab1",
                                    igv_dir_name = "IGV",
                                    ab1_dir_name = "AB1",
                                    readme_name = "README.txt",
                                    chinese_readme_name = "README.zh-CN.txt",
                                    overwrite = TRUE) {
  check_dir_arg(result_dir, "result_dir")
  check_scalar_character(output_dir, "output_dir")
  check_scalar_character(variant_all_name, "variant_all_name")
  check_scalar_character(barcode_pattern, "barcode_pattern")
  check_scalar_character(sample_length_plot_pattern, "sample_length_plot_pattern")
  check_scalar_character(readme_name, "readme_name")
  check_logical_scalar(include_igv, "include_igv")
  check_logical_scalar(include_ab1, "include_ab1")
  check_scalar_character(ab1_name_template, "ab1_name_template")
  check_scalar_character(igv_dir_name, "igv_dir_name")
  check_scalar_character(ab1_dir_name, "ab1_dir_name")
  if (!is.null(chinese_readme_name)) {
    check_scalar_character(chinese_readme_name, "chinese_readme_name")
  }
  check_logical_scalar(include_execution, "include_execution")
  check_logical_scalar(overwrite, "overwrite")

  result_dir <- normalizePath(result_dir, mustWork = TRUE)
  if (!is.null(sample_map)) {
    check_file_arg(sample_map, "sample_map")
    sample_map <- normalizePath(sample_map, mustWork = TRUE)
  }
  if (!is.null(fastq_pass_trim_dir)) {
    check_dir_arg(fastq_pass_trim_dir, "fastq_pass_trim_dir")
    fastq_pass_trim_dir <- normalizePath(fastq_pass_trim_dir, mustWork = TRUE)
  }

  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  output_dir <- normalizePath(output_dir, mustWork = TRUE)

  barcode_dirs <- list.dirs(result_dir, recursive = FALSE, full.names = TRUE)
  barcode_dirs <- barcode_dirs[grepl(barcode_pattern, basename(barcode_dirs))]
  barcode_dirs <- sort(barcode_dirs)

  items <- data.frame(
    label = character(),
    source = character(),
    destination = character(),
    type = character(),
    exists = logical(),
    copied = logical(),
    stringsAsFactors = FALSE
  )

  items <- rbind(
    items,
    collect_item(
      label = "variant_all",
      source = file.path(result_dir, variant_all_name),
      destination = file.path(output_dir, variant_all_name),
      type = "file",
      overwrite = overwrite
    )
  )

  if (!is.null(sample_map)) {
    items <- rbind(
      items,
      collect_item(
        label = "sample_map",
        source = sample_map,
        destination = file.path(output_dir, basename(sample_map)),
        type = "file",
        overwrite = overwrite
      )
    )
  }

  for (barcode_dir in barcode_dirs) {
    barcode_name <- basename(barcode_dir)
    items <- rbind(
      items,
      collect_item(
        label = barcode_name,
        source = barcode_dir,
        destination = file.path(output_dir, barcode_name),
        type = "directory",
        overwrite = overwrite
      )
    )

    if (!is.null(fastq_pass_trim_dir)) {
      plot_files <- find_sample_length_plots(
        fastq_pass_trim_dir = fastq_pass_trim_dir,
        barcode_name = barcode_name,
        pattern = sample_length_plot_pattern
      )
      for (plot_file in plot_files) {
        items <- rbind(
          items,
          collect_item(
            label = paste0(barcode_name, "_read_length_plot"),
            source = plot_file,
            destination = file.path(output_dir, barcode_name, basename(plot_file)),
            type = "file",
            overwrite = overwrite
          )
        )
      }
    }
  }

  if (isTRUE(include_execution)) {
    items <- rbind(
      items,
      collect_item(
        label = "execution",
        source = file.path(result_dir, "execution"),
        destination = file.path(output_dir, "execution"),
        type = "directory",
        overwrite = overwrite
      )
    )
  }

  readme_path <- file.path(output_dir, readme_name)
  writeLines(
    variant_results_readme(
      variant_all_name = variant_all_name,
      sample_map_name = if (is.null(sample_map)) NULL else basename(sample_map),
      barcode_names = basename(barcode_dirs),
      include_sample_length_plots = !is.null(fastq_pass_trim_dir),
      include_execution = include_execution,
      include_igv = include_igv,
      include_ab1 = include_ab1,
      ab1_name_template = ab1_name_template,
      igv_dir_name = igv_dir_name,
      ab1_dir_name = ab1_dir_name
    ),
    readme_path
  )
  items <- rbind(items, data.frame(
    label = "README",
    source = NA_character_,
    destination = readme_path,
    type = "file",
    exists = TRUE,
    copied = TRUE,
    stringsAsFactors = FALSE
  ))

  if (!is.null(chinese_readme_name)) {
    chinese_readme_path <- file.path(output_dir, chinese_readme_name)
    writeLines(
      variant_results_readme_zh(
        variant_all_name = variant_all_name,
        sample_map_name = if (is.null(sample_map)) NULL else basename(sample_map),
        barcode_names = basename(barcode_dirs),
        include_sample_length_plots = !is.null(fastq_pass_trim_dir),
        include_execution = include_execution,
        include_igv = include_igv,
        include_ab1 = include_ab1,
        ab1_name_template = ab1_name_template,
        igv_dir_name = igv_dir_name,
        ab1_dir_name = ab1_dir_name
      ),
      chinese_readme_path
    )
    items <- rbind(items, data.frame(
      label = "README_zh_CN",
      source = NA_character_,
      destination = chinese_readme_path,
      type = "file",
      exists = TRUE,
      copied = TRUE,
      stringsAsFactors = FALSE
    ))
  }

  invisible(items)
}

variant_results_readme <- function(variant_all_name,
                                   sample_map_name,
                                   barcode_names,
                                   include_sample_length_plots,
                                   include_execution,
                                   include_igv,
                                   include_ab1,
                                   ab1_name_template,
                                   igv_dir_name,
                                   ab1_dir_name) {
  lines <- c(
    "Amplicon variant final results",
    "==============================",
    "",
    "Recommended file",
    "----------------",
    paste0(
      "- ",
      variant_all_name,
      ": merged variant table for all barcode folders in this group."
    ),
    "",
    "Variant table columns",
    "---------------------",
    "- CHROM: reference sequence name used by VCF/BAM/IGV, usually the sanitized wf-amplicon name.",
    "- reference_name_original: original FASTA record name from the user-supplied reference.",
    "- reference_name_sanitized: sanitized FASTA record name used by wf-amplicon, VCF, BAM, and IGV.",
    "- POS: 1-based variant position on the reference.",
    "- REF: reference allele.",
    "- ALT: alternative allele.",
    "- QUAL: variant quality score from the VCF.",
    "- FILTER: VCF filter status.",
    "- Type: variant type inferred from REF and ALT, such as SNP, INDEL, MNP, OTHER, or REF.",
    "- ref_depth_downsampled: strand-summed reference allele support from medaka/wf-amplicon SR.",
    "- alt_depth_downsampled: strand-summed alternative allele support from medaka/wf-amplicon SR.",
    "- variant_percent: alt_depth_downsampled / (ref_depth_downsampled + alt_depth_downsampled) * 100.",
    "- sampleID: VCF sample column name, usually the barcode ID.",
    "- ref_upstream_20bp: 20 bp reference sequence upstream of the edited REF interval.",
    "- ref_downstream_20bp: 20 bp reference sequence downstream of the edited REF interval.",
    "",
    "Other files",
    "-----------"
  )
  if (!is.null(sample_map_name)) {
    lines <- c(
      lines,
      paste0(
        "- ",
        sample_map_name,
        ": barcode-to-sample mapping table. Use this file to match barcode folders to sample names."
      )
    )
  }

  lines <- c(lines, "", "Barcode folders", "---------------")
  if (length(barcode_names) > 0L) {
    lines <- c(
      lines,
      "- barcode*/: per-barcode results copied from the workflow output.",
      "- barcode*/variant.tsv: simplified variant table generated from barcode*/variants/medaka.annotated.vcf.gz.",
      "- barcode*/variants/medaka.annotated.vcf.gz: original medaka annotated VCF from wf-amplicon.",
      "- barcode*/alignments/*.bam: read alignments for the barcode.",
      "- barcode*/alignments/*.bam.bai: BAM index files.",
      if (isTRUE(include_igv)) {
        paste0(
          "- barcode*/",
          igv_dir_name,
          "/<barcode>.<reference>.*: IGV alignment snapshot images generated against the reference FASTA."
        )
      },
      if (isTRUE(include_ab1)) {
        paste0(
          "- barcode*/",
          ab1_dir_name,
          "/",
          sub("[{]reference[}]", "<reference>", sub("[{]barcode[}]", "<barcode>", ab1_name_template)),
          ": synthetic Sanger-style AB1 chromatogram generated from the barcode BAM and reference FASTA."
        )
      },
      if (isTRUE(include_sample_length_plots)) {
        "- barcode*/Distribution_seqLength__*.png: per-barcode read length distribution plot generated from filtered reads."
      },
      "",
      "Included barcode folders:",
      paste0("- ", barcode_names)
    )
  } else {
    lines <- c(lines, "- No barcode folders were found in the source result directory.")
  }

  if (isTRUE(include_execution)) {
    lines <- c(
      lines,
      "",
      "Execution metadata",
      "------------------",
      "- execution/: Nextflow execution report, timeline, and trace files when present."
    )
  }

  c(lines, "")
}

variant_results_readme_zh <- function(variant_all_name,
                                      sample_map_name,
                                      barcode_names,
                                      include_sample_length_plots,
                                      include_execution,
                                      include_igv,
                                      include_ab1,
                                      ab1_name_template,
                                      igv_dir_name,
                                      ab1_dir_name) {
  lines <- c(
    "扩增子变异检测最终结果",
    "======================",
    "",
    "推荐使用的文件",
    "--------------",
    paste0(
      "- ",
      variant_all_name,
      "：该分组内所有 barcode 的变异结果汇总表。"
    ),
    "",
    "变异表字段说明",
    "--------------",
    "- CHROM：VCF/BAM/IGV 实际使用的参考序列名称，通常是 wf-amplicon 校正后的名称。",
    "- reference_name_original：用户提供的原始参考 FASTA record 名称。",
    "- reference_name_sanitized：wf-amplicon、VCF、BAM 和 IGV 实际使用的校正后参考序列名称。",
    "- POS：变异在参考序列上的 1-based 位置。",
    "- REF：参考等位基因。",
    "- ALT：替代等位基因。",
    "- QUAL：VCF 中记录的变异质量值。",
    "- FILTER：VCF 过滤状态。",
    "- Type：根据 REF 和 ALT 推断的变异类型，例如 SNP、INDEL、MNP、OTHER 或 REF。",
    "- ref_depth_downsampled：来自 medaka/wf-amplicon SR 字段的参考等位基因支持数，合并正反链。",
    "- alt_depth_downsampled：来自 medaka/wf-amplicon SR 字段的替代等位基因支持数，合并正反链。",
    "- variant_percent：alt_depth_downsampled / (ref_depth_downsampled + alt_depth_downsampled) * 100。",
    "- sampleID：VCF 样本列名称，通常为 barcode ID。",
    "- ref_upstream_20bp：参考序列中编辑 REF 区间上游 20 bp 序列。",
    "- ref_downstream_20bp：参考序列中编辑 REF 区间下游 20 bp 序列。",
    "",
    "其他文件",
    "--------"
  )
  if (!is.null(sample_map_name)) {
    lines <- c(
      lines,
      paste0(
        "- ",
        sample_map_name,
        "：barcode 与样本名称的对应表，可用于把 barcode 文件夹对应到具体样本。"
      )
    )
  }

  lines <- c(lines, "", "Barcode 文件夹", "--------------")
  if (length(barcode_names) > 0L) {
    lines <- c(
      lines,
      "- barcode*/：从流程结果目录复制得到的各 barcode 结果文件夹。",
      "- barcode*/variant.tsv：由 barcode*/variants/medaka.annotated.vcf.gz 生成的简化变异表。",
      "- barcode*/variants/medaka.annotated.vcf.gz：wf-amplicon/medaka 生成的原始注释 VCF。",
      "- barcode*/alignments/*.bam：该 barcode 的 reads 比对结果。",
      "- barcode*/alignments/*.bam.bai：BAM 索引文件。",
      if (isTRUE(include_igv)) {
        paste0(
          "- barcode*/",
          igv_dir_name,
          "/<barcode>.<reference>.*：基于参考 FASTA 生成的 IGV 比对截图。"
        )
      },
      if (isTRUE(include_ab1)) {
        paste0(
          "- barcode*/",
          ab1_dir_name,
          "/",
          sub("[{]reference[}]", "<reference>", sub("[{]barcode[}]", "<barcode>", ab1_name_template)),
          "：由该 barcode 的 BAM 文件和参考 FASTA 合成的 Sanger 风格 AB1 峰图文件。"
        )
      },
      if (isTRUE(include_sample_length_plots)) {
        "- barcode*/Distribution_seqLength__*.png：基于过滤后 reads 生成的每个 barcode 的读长分布图。"
      },
      "",
      "包含的 barcode 文件夹：",
      paste0("- ", barcode_names)
    )
  } else {
    lines <- c(lines, "- 在源结果目录中没有找到 barcode 文件夹。")
  }

  if (isTRUE(include_execution)) {
    lines <- c(
      lines,
      "",
      "运行信息",
      "--------",
      "- execution/：如果源结果中存在，则包含 Nextflow 的运行报告、时间线和 trace 文件。"
    )
  }

  c(lines, "")
}
